title: J2S Inserts
description: Inserts imprimés en 3D pour jeux de société
url: "https://skvvib-j2s.github.io"
baseurl: ""

collections:
  products:
    output: true
    permalink: /produits/:name/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product